### ISSUE TITLE
Update StreamingTemplateRenderer to support Rails 6

### ISSUE THREAD

**Issue by sdemjanenko** [malomalo/turbostreamer#15]
When using Tubrostreamer in a Rails 6 app I get the error:
```
wrong number of arguments (given 4, expected 1..3) 
```
trace:
```
turbostreamer (1.7.0) ext/actionview/streaming_template_renderer.rb:4:in `render_template'
actionview (6.0.1) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.1) lib/action_view/renderer/renderer.rb:42:in `render_body'
actionpack (6.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (6.0.1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (6.0.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
activerecord (6.0.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
app/controllers/newrelic_demo_controller.rb:3:in `items'  # my controller action
```
It looks like ActionView now passes `context` as the first argument to `render_template` which doesn't match the call syntax of `render_template` in `StreamingTemplateRenderer`.

**Comment by malomalo** [comment]
👍 on it, sorry for some reason I was not getting notifications about my personal github account
